export const projectData = [
  {
    id: 1,
    icon: "<AiFillGithub />",
    ivon1: "<FaSignOutAlt />",
    title: "React Website ",
    subtitle: "SAFE HOUSE",
    button1: "React ",
    button2: "Styled Components",
    img: require("../../assets/projects/project-1.jpeg").default,
    link: "https://github.com/ernazar151020/safe-house",
    demo: "https://ernazar151020.github.io/safe-house/",
  },
  {
    id: 2,
    icon: " <AiFillGithub />",
    ivon1: "<FaSignOutAlt />",
    title: "React Website ",
    subtitle: "Ugmonk Website",
    button1: "React",
    button2: "Styled Components",
    img: require("../../assets/projects/project-2.jpeg").default,
    link: "https://github.com/ernazar151020/react-website",
    demo: "https://ernazar151020.github.io/react-website/",
  },
  {
    id: 3,
    icon: "<AiFillGithub />",
    ivon1: "<FaSignOutAlt />",
    title: "React Website ",
    button1: "React",
    button2: "Styled Components",
    img: require("../../assets/projects/project-3.jpeg").default,
    subtitle: "Bank Website",
    link: "https://github.com/ernazar151020/ernazar-react-bank-website",
    demo: "https://react-banking-website.netlify.app/",
  },
  {
    id: 4,
    icon: "<AiFillGithub />",
    ivon1: "<FaSignOutAlt />",
    title: "HTML / CSS/ JS ",
    button1: "HTML / CSS /JS",
    button2: "BOOTSRAP",
    img: require("../../assets/projects/project-4.jpeg").default,
    subtitle: "Sushi Website",
    link: "https://github.com/ernazar151020/sushi",
    demo: "https://sushi-ernazar.netlify.app/",
  },
  {
    id: 5,
    icon: "<AiFillGithub />",
    ivon1: "<FaSignOutAlt />",
    title: "HTML / CSS ",
    button1: "HTML / CSS / JS",
    button2: "BOOTSRAP",
    img: require("../../assets/projects/project-5.jpeg").default,
    subtitle: "SHOPPING CART",
    link: "https://github.com/ernazar151020/cake-shopping-cart",
    demo: "https://bootsrap-shopping-cart.netlify.app/",
  },
  {
    id: 6,
    icon: "<AiFillGithub />",
    ivon1: "<FaSignOutAlt />",
    title: "React Website ",
    button1: "REACT",
    button2: "Styled Components",
    img: require("../../assets/projects/project-6.jpeg").default,
    subtitle: "THRIVETALK WEBSITE",
    link: "https://github.com/ernazar151020/react-website-Thrivetalk",
    demo: "https://thrivetalk-react-website.netlify.app//",
  },
  {
    id: 7,
    icon: "<AiFillGithub />",
    ivon1: "<FaSignOutAlt />",
    title: "React Project ",
    button1: "React",
    button2: "React HOOKS",
    img: require("../../assets/projects/project-7.jpeg").default,
    subtitle: "ORDER BOX",
    link: "https://github.com/ernazar151020/order-box",
    demo: "https://ernazar151020.github.io/order-box/",
  },
  {
    id: 8,
    icon: "<AiFillGithub />",
    ivon1: "<FaSignOutAlt />",
    title: "React Project ",
    button1: "React",
    button2: "React HOOKS",
    img: require("../../assets/projects/project-7.jpeg").default,
    subtitle: "TO DO LIST ",
    link: "https://github.com/ernazar151020/react-todoList",
    demo: "https://ernazar151020.github.io/react-todoList/",
  },
]
